# -*- coding: utf-8 -*-
import json
W={r['rank']:r for r in json.load(open('/tmp/claude-0/-home-user/e4610181-73c9-5b97-9776-a971b4d99e53/scratchpad/vue_study/in/winners_all.json'))}
def base(rank):
    r=W[rank]; return dict(rank=rank,id_video=r['best'],titulo_meta=r['titles'][0] if r['titles'] else '',landing=r['landing'],duracion_s=round(r['duration']),metricas=dict(anuncios=r['ads'],videos=r['videos'],dias_totales=r['total_run'],dias_max=r['max_run'],variantes=r['variants'],primera_fecha=r['first'],ultima_fecha=r['last']),transcripcion_en=r['text'])
def E(si,sf,b,d,p,f): return dict(seg_ini=si,seg_fin=sf,bloque=b,dice=d,pasa_en_pantalla=p,funcion=f)
def F(en,es): return dict(en=en,es=es)
A=[]
# R13 (familia R56): «no es suciedad, es grasa» + imán + antes/después
a=base(13); a.update(dict(traduccion_es="Si ves estos puntitos en la nariz: no es suciedad, no son puntos negros, es grasa acumulada, se llaman filamentos sebáceos. Probablemente por eso nada de lo que has probado ha funcionado. Ni los exfoliantes, ni las tiras, ni los limpiadores caros. No resuelven el problema: solo cabrean a tu piel. Es un ciclo: limpia unas horas y los puntitos vuelven. Porque los filamentos sebáceos son canales de grasa que se rellenan solos. Esto es lo que funciona de verdad: parches de nariz de hidrocoloide. Funcionan como un imán: absorben el exceso de grasa desde dentro del poro mientras duermes. Sin arrancar, sin rojeces, sin batalla diaria. Mira mi antes y después. Ya no me despierto con los mismos puntitos de siempre. Están de oferta ahora mismo con 60 días de garantía. Pincha abajo y controla tu nariz de una vez.",
estructura=[E(0,3,"gancho triple negación","If you see these dots on your nose, it's not dirt, it's not blackheads, it's oil buildup","Macro nariz (inferido).","Tres negaciones rápidas: ritmo y reencuadre en 3 s."),E(3,12,"absolución","That's probably why nothing you've tried has worked… they're just making your skin angrier","Botes (inferido).","No eres tú + los productos «cabrean» la piel."),E(12,18,"ciclo","It's a cycle clear for a few hours, then the dots are back","Mañana/noche (inferido).","Recurrencia."),E(18,29,"mecanismo imán","They work like a magnet, absorb the excess oil from inside your pores while you sleep, no ripping, no redness, no daily battle","Aplicación (inferido).","Solución + mantra."),E(29,34,"prueba","Check my before and after. Now I no longer wake up to the same old dots.","Antes/después (inferido).","Visual."),E(34,40,"oferta + cta","on sale right now with a 60 day money back guarantee. So click below and finally get your nose under control.","Web (inferido).","Cierre con verbo de control.")],
gancho=dict(tipo="Triple negación",texto_en="it's not dirt, it's not blackheads, it's oil buildup",texto_es="no es suciedad, no son puntos negros, es grasa",por_que_para_el_scroll="El ritmo de tres golpes y la corrección doble (no suciedad, no puntos negros) en 3 segundos: máxima información por segundo."),
reencuadre="Grasa que se rellena, no suciedad.",mecanismo="Imán desde dentro, de noche; tres negaciones.",prueba=["Antes/después","«Ya no me despierto con los mismos puntitos»"],objeciones_resueltas=["«Es suciedad, me lavo más» → no es suciedad","«Vuelven» → ciclo","«Irrita» → sin rojeces"],disparadores_emocionales=["Alivio","Control («get your nose under control»)"],tecnicas_persuasion=["Triple negación","Absolución","Metáfora imán","Mantra de tres","CTA con verbo de control"],
frases_clave=[F("it's not dirt, it's not blackheads, it's oil buildup","no es suciedad, no son puntos negros: es grasa"),F("they're just making your skin angrier","solo cabrean a tu piel"),F("finally get your nose under control","controla tu nariz de una vez")],
oferta_cta="Oferta + 60 días + click below.",
por_que_funciona="22 anuncios y 43 variantes en 8 meses: la versión más compacta (40 s) de la plantilla maestra, con el gancho más rápido del ranking (tres negaciones). Se estiró a 115 s en R56 (11 anuncios, 88 días) y funcionó peor por segundo: la evidencia de que 40 s es el punto óptimo de esta estructura.",
senales_de_conversion="22 anuncios, 8 vídeos, 43 variantes, 782 días (ene–ago 2026); la versión larga R56 acumuló 418 días más.",
que_copiar_para_nocta=["Gancho de triple negación","«Cabrean a tu piel»","CTA «controla tu nariz»","Mantener 40 s"],que_no_se_puede_decir_en_espana=["Ninguno grave; «on sale» solo si hay oferta activa en el CRM"],adaptacion_espana="Todos. Muy bueno para Reels."))
A.append(a)
# R15 (3 razones + 1 pega)
a=base(15); a.update(dict(traduccion_es="Tres razones por las que me encantan estos parches y una por la que no. Uno: funcionan rápido. Y cuando digo rápido es que ves los poros más cerrados y la nariz lisa con un solo uso. Dos: los parches van a por los filamentos sebáceos, donde se acumula el exceso de grasa; reducir el sebo es la clave de una piel más limpia a largo plazo. Tres: no llevan alcohol ni ingredientes comedogénicos, que ya es más de lo que ponen otras marcas en sus productos; su hidrocoloide es cruelty free y suave con la piel. Y lo que no me gusta: que mi hermana me los roba para quitarse ella los poros tapados. Ahora están con un 30 % de descuento por tiempo limitado, así que cógelos mientras queden.",
estructura=[E(0,3,"gancho listicle con giro","Here are three reasons why I love these patches and one reason why I don't.","Caja en mano (inferido).","La «pega» anunciada crea curiosidad y credibilidad."),E(3,12,"razón 1: rapidez","they work fast… after just one use","Nariz lisa (inferido).","Beneficio inmediato."),E(12,24,"razón 2: mecanismo","target sebaceous filaments where excess oil builds up","Macro (inferido).","Racional."),E(24,33,"razón 3: ingredientes","don't contain alcohol-based or comedogenic ingredients… cruelty-free","Etiqueta (inferido).","Seguridad."),E(33,37,"la pega (humor)","my sister keeps stealing my patches","Hermana (inferido).","Prueba social disfrazada de queja."),E(37,40,"oferta","30% off for a limited time… while they're still in stock","Web (inferido).","Urgencia.")],
gancho=dict(tipo="Listicle con giro",texto_en="three reasons why I love these patches and one reason why I don't",texto_es="Tres razones por las que me encantan y una por la que no",por_que_para_el_scroll="La promesa de una pega desarma el escepticismo y obliga a quedarse hasta el final."),
reencuadre="Menos sebo = piel más limpia a largo plazo.",mecanismo="Va a por el sebo de los filamentos.",prueba=["Un solo uso","Ingredientes","La hermana (prueba social)"],objeciones_resueltas=["«¿Tarda?» → un uso","«¿Lleva cosas malas?» → sin alcohol ni comedogénicos","«¿Es un anuncio?» → hay una pega"],disparadores_emocionales=["Humor","Confianza"],tecnicas_persuasion=["Listicle","Pega falsa (humor)","Urgencia"],
frases_clave=[F("three reasons why I love… and one reason why I don't","tres razones por las que me encantan y una por la que no"),F("my sister keeps stealing my patches","mi hermana me los roba")],
oferta_cta="30 % por tiempo limitado.",
por_que_funciona="290 días con un solo vídeo. La «pega» final es la técnica más elegante del ranking: convierte la prueba social en broma y hace que el anuncio parezca una opinión. La razón 1 (resultado en un uso) es un claim fuerte que en España hay que suavizar.",
senales_de_conversion="12 anuncios, 1 vídeo, 16 variantes, 857 días; 290 días.",
que_copiar_para_nocta=["Listicle con pega final (humor)","Argumento de ingredientes (sin activos, sin alcohol)"],que_no_se_puede_decir_en_espana=["«pores tighten after just one use» → «por la mañana ves en el parche lo que ha salido»","«cruelty-free» solo si se puede acreditar"],adaptacion_espana="Bea. La hermana/compañera de piso que roba parches es muy español."))
A.append(a)
# R16 (hombres +35: familia R1)
a=base(16); a.update(dict(traduccion_es="La mayoría de los tíos de más de 35 cree que esto son puntos negros. No lo son. Se llaman filamentos sebáceos… (resto idéntico al nº 1).",
estructura=[E(0,3,"gancho identidad (hombre +35)","Most guys over 35 think these are blackheads, they're not.","Hombre 35–45 señalando la nariz (inferido).","Segmento con edad."),E(3,42,"resto","(idéntico al nº 1)","(idéntico)","Plantilla maestra.")],
gancho=dict(tipo="Identidad + edad + contradicción",texto_en="Most guys over 35 think these are blackheads, they're not.",texto_es="La mayoría de los tíos de más de 35 cree que esto son puntos negros. No lo son.",por_que_para_el_scroll="Nombrar edad y sexo en la primera frase filtra a la audiencia y la hace sentir aludida."),
reencuadre="El del nº 1.",mecanismo="El del nº 1.",prueba=["Las del nº 1"],objeciones_resueltas=["Las del nº 1"],disparadores_emocionales=["Identidad masculina madura"],tecnicas_persuasion=["Segmentación por edad y sexo en el gancho"],
frases_clave=[F("Most guys over 35 think these are blackheads","La mayoría de los tíos de más de 35 cree que esto son puntos negros")],oferta_cta="Garantía; «Finally Clear Skin for Guys».",
por_que_funciona="Demuestra que el guion nº 1 vende también a hombres de 35+ (214 días, 17 variantes) sin cambiar nada más que la primera frase. Para NOCTA: Álex (y su versión 35+) se atiende con la misma plantilla.",
senales_de_conversion="7 anuncios, 3 vídeos, 17 variantes, 818 días; 214 días máximo.",
que_copiar_para_nocta=["Versión Álex 35+ de la plantilla maestra"],que_no_se_puede_decir_en_espana=["Las del nº 1"],adaptacion_espana="«Tíos» para Álex; «hombres» para 40+."))
A.append(a)
# R17 (3 formas + precio de un rímel)
a=base(17); a.update(dict(traduccion_es="Si tus poros se ven así o así, no los estás cuidando bien. Tres formas de mantener los poros limpios sin dañar la piel. Uno: los poros grandes y los puntos negros aparecen cuando el exceso de grasa y las células muertas se quedan atrapadas; un parche nocturno ayuda a sacar esas impurezas mientras duermes. Dos: usa un parche con hidrocoloide; yo recomiendo los de Vue: funcionan como un imán para sacar grasa e impurezas sin frotar ni apretar. Tres: la constancia mantiene los poros limpios a largo plazo. Estos parches protegen la barrera natural de la piel mientras sacan impurezas. Además están hechos en Corea, el país líder en innovación en cuidado de la piel. Mi piel queda como la seda y mis poros son literalmente invisibles. Es muy satisfactorio ver el resultado en el parche por la mañana. Así que, si quieres unos poros mejores de la noche a la mañana por menos de lo que cuesta un rímel, tienes que probarlos. Te alegrarás de haberlo hecho.",
estructura=[E(0,4,"gancho visual doble","If your pores look like this or like this, you're not taking care of them properly.","Dos macros de nariz (inferido).","Dos imágenes = dos tipos de espectador."),E(4,30,"3 formas","1… overnight patch… 2… hydrocolloid… magnet… 3… consistent use","Rutina (inferido).","Consejo útil con el producto dentro."),E(30,40,"origen + resultado","made in Korea… skin feels like silk… pores literally invisible","Nariz (inferido).","Beneficio sensorial."),E(40,46,"prueba","It's so satisfying to see the results on the patch in the morning.","Parche usado (inferido).","Peel reveal."),E(46,53,"ancla precio + cta","less than the price of a mascara… You will be so glad you did.","Web (inferido).","Ancla barata.")],
gancho=dict(tipo="Reconocimiento visual doble",texto_en="If your pores look like this or like this",texto_es="Si tus poros se ven así… o así",por_que_para_el_scroll="Enseñar dos narices distintas duplica la probabilidad de que el espectador se reconozca."),
reencuadre="Cuidar ≠ atacar: consejos.",mecanismo="Imán + barrera intacta.",prueba=["Satisfacción del parche por la mañana","Piel como la seda"],objeciones_resueltas=["«Es caro» → menos que un rímel","«¿Cómo se usa?» → 3 pasos"],disparadores_emocionales=["Satisfacción","Aspiración («invisibles»)"],tecnicas_persuasion=["Doble reconocimiento","Consejo educativo","Ancla de precio cotidiano","Sensorialidad"],
frases_clave=[F("If your pores look like this or like this","Si tus poros se ven así… o así"),F("My skin feels like silk","La piel me queda como la seda"),F("for less than the price of a mascara","por menos de lo que cuesta un rímel")],
oferta_cta="Ancla de precio; garantía en el texto.",
por_que_funciona="287 días con un vídeo. Dos ideas que nadie más usa: el gancho con dos imágenes («así o así») y el ancla de precio cotidiano (un rímel). El formato «3 formas» convierte el anuncio en consejo. Claim a vigilar: «poros literalmente invisibles».",
senales_de_conversion="8 anuncios, 1 vídeo, 15 variantes, 846 días; 287 días.",
que_copiar_para_nocta=["Gancho «así… o así» con dos narices","«Por menos de lo que cuesta un rímel / un café» (pack de 2 = 1,87 €/noche)","Peel reveal como satisfacción"],que_no_se_puede_decir_en_espana=["«pores literally invisible» → «se notan mucho menos»"],adaptacion_espana="Bea y Marisol."))
A.append(a)
# R19 (después de los 40, anti-láser)
a=base(19); a.update(dict(traduccion_es="El secreto de unos poros lisos después de los 40 no es el láser. Si quieres pasar de puntitos visibles a una nariz lisa como el cristal, de brillo graso a un acabado mate, en vez de quemarte la piel con láser, estos parches de hidrocoloide usan un enfoque científico para ir a por lo que tapona los poros durante la noche, sin dañar la barrera. Los dermatólogos advierten de que el láser puede afinar la piel y debilitar la barrera con el tiempo. En solo tres semanas estos parches convierten los puntos negros rebeldes y el brillo en una piel lisa y limpia. Míralo: miles de mujeres de más de 40 dicen que es lo primero que de verdad les ha limpiado los poros. Pincha abajo para hasta un 45 % de descuento.",
estructura=[E(0,4,"gancho secreto + edad + anti-láser","The secret to smooth pores after 40 is not using a laser.","Mujer 40+ (inferido).","Edad + negación de la opción cara."),E(4,14,"transformación","from visible black dots to a glass smooth nose, from oily shine to matte glow","Antes/después (inferido).","Dos contrastes paralelos."),E(14,24,"autoridad contra el láser","Dermatologists warn that lasers can thin the skin","Rótulo (inferido).","Miedo racional."),E(24,31,"plazo + prueba","In just three weeks… Check it out","Antes/después (inferido).","Visual."),E(31,37,"prueba social + oferta","thousands of women over 40… up to 45% off","Web (inferido).","Cierre.")],
gancho=dict(tipo="Secreto + edad + anti-caro",texto_en="The secret to smooth pores after 40 is not using a laser.",texto_es="El secreto de unos poros lisos después de los 40 no es el láser.",por_que_para_el_scroll="«Secreto» + «después de los 40» + «no es el láser»: tres ganchos en una frase para Marisol."),
reencuadre="Lo agresivo envejece la piel.",mecanismo="Enfoque científico nocturno sin dañar la barrera.",prueba=["Transformación doble","3 semanas","Miles de mujeres 40+"],objeciones_resueltas=["«A mi edad solo funciona lo agresivo» → al revés"],disparadores_emocionales=["Miedo a envejecer la piel","Pertenencia 40+"],tecnicas_persuasion=["Paralelismo (de X a Y, de A a B)","Autoridad negativa (contra el láser)","Plazo","Prueba social segmentada","Descuento alto"],
frases_clave=[F("from visible black dots to a glass smooth nose, from oily shine to matte glow","de puntitos visibles a nariz lisa; de brillo a mate"),F("Harsh treatments don't age well on the skin","Lo agresivo envejece mal (R38)")],
oferta_cta="Hasta 45 %.",
por_que_funciona="Familia con R38 («Harsh treatments don't age well») y R41: el mismo cuerpo con tres ganchos distintos, 30 anuncios en total. Es EL guion de Marisol: edad explícita, miedo a dañar la piel madura, paralelismo de transformación y prueba social de su grupo.",
senales_de_conversion="10 anuncios, 7 vídeos, 11 variantes, 749 días; con R38 y R41 ≈ 32 anuncios.",
que_copiar_para_nocta=["Gancho por edad para Marisol","Paralelismo «de X a Y»","Contra láser/cabina con precio real"],que_no_se_puede_decir_en_espana=["«Dermatologists warn» → «los tratamientos agresivos pueden dañar la barrera» sin citar médicos","«glass smooth» → «mucho más lisa»"],adaptacion_espana="Marisol."))
A.append(a)
# R20 (22 s, ultracorto)
a=base(20); a.update(dict(traduccion_es="Si notas puntos negros, no los aprietes. Usa esto. Son parches de nariz de hidrocoloide de Vue. Absorben las impurezas con hidrocoloide que atrapa con suavidad el exceso de grasa y sebo para limpiar los poros. Mi piel se ve mucho más limpia y lisa cuando los uso. Cómpralos solo si estás lista para tener la piel lisa y limpia.",
estructura=[E(0,3,"gancho orden + sustitución","If you notice blackheads, do not squeeze them. Instead, use one of these.","Parche en mano (inferido).","Orden + objeto."),E(3,14,"mecanismo mínimo","hydrocolloid that gently trap excess oil and sebum","Aplicación (inferido).","Una frase."),E(14,22,"resultado + cta con reto","cleaner and smoother… only if you're ready","Nariz (inferido).","CTA que reta.")],
gancho=dict(tipo="Orden + sustitución",texto_en="If you notice blackheads, do not squeeze them. Instead, use one of these.",texto_es="Si te ves puntos negros, no los aprietes. Ponte esto.",por_que_para_el_scroll="Da la solución en el segundo 2: para gente que ya conoce el problema."),
reencuadre="Apretar → parche.",mecanismo="Atrapa grasa y sebo.",prueba=["Ninguna visual explícita"],objeciones_resueltas=["Ninguna: es un recordatorio"],disparadores_emocionales=["Reto («solo si estás lista»)"],tecnicas_persuasion=["Brevedad","CTA de reto (takeaway)"],
frases_clave=[F("Instead, use one of these.","Ponte esto."),F("only if you're ready to have smooth and clean skin","solo si estás lista para tener la piel limpia")],
oferta_cta="30 % en el texto; 254 días.",
por_que_funciona="22 segundos, 254 días, 19 variantes: la prueba de que un anuncio ultracorto funciona como recordatorio/retargeting cuando el mercado ya conoce el reencuadre. Para NOCTA es el formato para Reels de 15 s y para el retargeting por email.",
senales_de_conversion="10 anuncios, 1 vídeo, 19 variantes, 800 días; 254 días.",
que_copiar_para_nocta=["Formato de 15–20 s: orden + objeto + una frase de mecanismo + reto"],que_no_se_puede_decir_en_espana=["«effectively clear your pores» → «ayudan a limpiar los poros»"],adaptacion_espana="Bea; TikTok/Reels."))
A.append(a)
# R21 («la verdad que nadie te cuenta»)
a=base(21); a.update(dict(traduccion_es="Esta es la verdad sobre esos puntos negros de la nariz que nadie te cuenta. Chicos, escuchad. Esos puntitos y poros no son solo suciedad: son grasa oxidada atrapada al fondo de los poros. Los limpiadores normales no llegan; no pueden bajar tanto. Por eso los parches de hidrocoloide están llamando tanto la atención ahora mismo: funcionan como un imán, sacando las impurezas profundas mientras duermes. Sin frotar, sin apretar, sin líos. Solo poros limpios por la mañana, así de simple. A mí me bastó un paquete para ver la diferencia. ¿Sigues con dudas? Pruébalos tú mismo. Yo uso los de Vue porque ofrecen garantía de devolución si no quedas contento.",
estructura=[E(0,4,"gancho secreto","Here's the truth about those black dots on your nose that nobody talks about. Guys, listen up.","Hombre a cámara (inferido).","Secreto + llamada al grupo."),E(4,14,"reencuadre grasa oxidada","not just dirt. They're oxidized oil trapped deep in your pores","Macro (inferido).","Explicación."),E(14,26,"mecanismo imán","like a magnet, pulling out all the deep impurities while you sleep. No scrubbing, no squeezing, no mess.","Parche (inferido).","Solución + tres negaciones."),E(26,32,"prueba","One pack is all it took for me to see the difference.","Nariz (inferido).","Resultado en un paquete."),E(32,38,"reto + garantía","Still skeptical? Try them yourself… money-back guarantee","Web (inferido).","Cierre.")],
gancho=dict(tipo="Secreto + llamada al grupo",texto_en="Here's the truth about those black dots on your nose that nobody talks about. Guys, listen up.",texto_es="La verdad sobre esos puntos negros de la nariz que nadie te cuenta. Chicos, atentos.",por_que_para_el_scroll="Promesa de información oculta + interpelación directa al grupo masculino."),
reencuadre="Grasa oxidada profunda, no suciedad.",mecanismo="Imán profundo de noche.",prueba=["Un paquete bastó"],objeciones_resueltas=["«Me lavo la cara» → no llega al fondo","«Sigo con dudas» → pruébalo, garantía"],disparadores_emocionales=["Curiosidad (secreto)","Reto"],tecnicas_persuasion=["Secreto","Interpelación","Metáfora","Reto al escéptico"],
frases_clave=[F("that nobody talks about","que nadie te cuenta"),F("Regular cleansers… can't reach deep enough","Los limpiadores no llegan tan abajo"),F("Still skeptical? Try them yourself.","¿Sigues con dudas? Pruébalo.")],
oferta_cta="Garantía; 30 % en el texto.",
por_que_funciona="223 días: la versión masculina del reencuadre con la palabra «secreto». El mismo guion murió en 0 días con otra persona (ver perdedores): la ejecución importa tanto como el texto.",
senales_de_conversion="12 anuncios, 5 vídeos, 12 variantes, 700 días; 223 días.",
que_copiar_para_nocta=["Gancho «la verdad que nadie te cuenta» para Álex","Reto al escéptico antes de la garantía"],que_no_se_puede_decir_en_espana=["Ninguno grave"],adaptacion_espana="Álex."))
A.append(a)
# R23 (consecuencia + white spots)
a=base(23); a.update(dict(traduccion_es="Esta es la consecuencia de no cuidar bien mis poros. Te enseño lo que me funcionó: parches de nariz. Disuelven las impurezas con suavidad y absorben toda la porquería de los poros. Tenía los poros dilatados y tapados porque los trataba como puntos negros, pero en realidad eran filamentos sebáceos, que cuestan mucho de quitar. Uso estos parches cada semana. Cuando me lo quito, la nariz queda lisísima y los poros parecen mucho más pequeños. Aquí puedes ver los puntos blancos que se han formado en el parche. Pruébalos. Me lo agradecerás.",
estructura=[E(0,3,"gancho consecuencia","This is the consequence of not taking care of my pores the right way.","Macro nariz (inferido).","Muestra el daño primero."),E(3,8,"promesa","I'll show you what worked for me. Nose patches.","Caja (inferido).","Solución nombrada pronto."),E(8,18,"reencuadre personal","I was treating them like they were blackheads. But they were actually sebaceous filaments","Macro (inferido).","Diagnóstico."),E(18,24,"uso + resultado","every week… so smooth… pores just feel a lot smaller","Nariz (inferido).","Frecuencia real (semanal)."),E(24,27,"prueba + cta","Here you can see the white spots that formed on the patch. Go try them.","Parche usado (inferido).","Peel reveal.")],
gancho=dict(tipo="Consecuencia (mostrar el daño)",texto_en="This is the consequence of not taking care of my pores the right way.",texto_es="Esto es lo que pasa por no cuidar bien los poros.",por_que_para_el_scroll="Muestra la nariz «mal» en el segundo 0 con una frase de culpa asumida."),
reencuadre="Filamentos, no puntos negros.",mecanismo="Absorbe la porquería.",prueba=["Puntos blancos en el parche (explícito)","Uso semanal"],objeciones_resueltas=["«¿Cada cuánto?» → cada semana"],disparadores_emocionales=["Vergüenza asumida","Satisfacción"],tecnicas_persuasion=["Mostrar el daño","Frecuencia honesta","Peel reveal"],
frases_clave=[F("This is the consequence of not taking care of my pores","Esto es lo que pasa por no cuidar los poros"),F("Here you can see the white spots that formed on the patch","Mira los puntos blancos que se han formado en el parche")],
oferta_cta="30 %; 290 días.",
por_que_funciona="27 segundos y 290 días: enseña el daño en el segundo 0 y el parche blanco en el 24. Es el guion con menos palabras por prueba visual del ranking; y dice «cada semana», que es la frecuencia real de uso (2–3 noches por semana): honesto y coherente con la caja de 8.",
senales_de_conversion="6 anuncios, 1 vídeo, 7 variantes, 756 días; 290 días.",
que_copiar_para_nocta=["Empezar por el daño","Decir la frecuencia real (2–3 noches/semana)","Puntos blancos en el parche como cierre"],que_no_se_puede_decir_en_espana=["«dissolve impurities» → «absorben»"],adaptacion_espana="Bea."))
A.append(a)
# R25 (Dúo: los dos únicos productos)
a=base(25); a.update(dict(traduccion_es="Te voy a enseñar los dos únicos productos que necesitas para transformar tu nariz de esto a esto. El tónico con salicílico está diseñado para destapar poros y alisar la piel; con ácido salicílico y glicólico exfolia, refina la textura y mantiene los poros limpios. Y combinado con sus parches de nariz de hidrocoloide, el dúo absorbe el exceso de grasa y saca las impurezas durante la noche. A diferencia de los exfoliantes agresivos o las extracciones, estos parches no dañan la barrera de la piel, así que van bien incluso para piel muy, muy sensible. Ahora ofrecen un pack de cuidado de poros para llevarte los dos juntos. ¿Tienes puntos negros o textura irregular? Es el momento de probarlo. Además, 60 días de garantía si no quedas contenta.",
estructura=[E(0,4,"gancho «los dos únicos»","the only two products you need to transform your nose from this to this","Antes/después (inferido).","Simplicidad + transformación."),E(4,18,"paso 1","Boost with salicylic toner… exfoliates, refines texture","Tónico (inferido).","Mecanismo 1."),E(18,30,"paso 2","paired with their best-selling hydrocolloid nose patches… absorbs excess oils… overnight","Parche (inferido).","Mecanismo 2."),E(30,40,"seguridad","without damaging your skin barrier… really, really sensitive skin","Piel (inferido).","Objeción sensibilidad."),E(40,56,"pack + garantía","exclusive pore care bundle… 60-day money-back guarantee","Web (inferido).","Cierre de pack.")],
gancho=dict(tipo="Simplicidad («los dos únicos») + transformación",texto_en="the only two products you need to transform your nose from this to this",texto_es="Los dos únicos productos que necesitas para pasar de esto a esto",por_que_para_el_scroll="Reduce el skincare a dos cosas y enseña el antes/después en el segundo 2."),
reencuadre="No necesitas 10 pasos: dos.",mecanismo="Exfoliar + absorber.",prueba=["Antes/después","Best-seller"],objeciones_resueltas=["«Piel sensible» → sin dañar la barrera","«Muchos pasos» → solo dos"],disparadores_emocionales=["Alivio de simplicidad"],tecnicas_persuasion=["Reducción («los dos únicos»)","Sistema de dos pasos","Pack"],
frases_clave=[F("the only two products you need","los dos únicos productos que necesitas"),F("from this to this","de esto a esto")],
oferta_cta="Pack exclusivo + 60 días; 294 días.",
por_que_funciona="El anuncio de Dúo más longevo (294 días). Vende el pack con un argumento de simplicidad («solo dos») y un mecanismo en dos pasos que se entiende. Para NOCTA es el molde del anuncio del Dúo Noche (nariz + granos): «los dos únicos parches que necesitas».",
senales_de_conversion="8 anuncios, 1 vídeo, 8 variantes, 732 días; 294 días.",
que_copiar_para_nocta=["«Los dos únicos» para el Dúo Noche","Argumento de piel sensible"],que_no_se_puede_decir_en_espana=["Ninguno grave"],adaptacion_espana="Marisol y Bea."))
A.append(a)
# R26 (15 s, maquillaje)
a=base(26); a.update(dict(traduccion_es="¿Te da vergüenza que el maquillaje se te vea así? Te ayudamos: ponte parches de nariz por la noche. Sacan todas las impurezas y dejan que los poros funcionen bien. Con dos semanas de uso tendrás la piel lisa y luminosa y la nariz limpia. Pincha abajo para un 30 % de descuento.",
estructura=[E(0,3,"gancho vergüenza maquillaje","Embarrassed of makeup looking like this.","Base cuarteada en la nariz (inferido).","Problema visual concreto."),E(3,10,"solución","apply nose patches overnight","Parche (inferido).","Directo."),E(10,15,"plazo + oferta","after two weeks… 30% off","Web (inferido).","Cierre.")],
gancho=dict(tipo="Vergüenza + prueba visual del maquillaje",texto_en="Embarrassed of makeup looking like this.",texto_es="¿Te da vergüenza que el maquillaje se te vea así?",por_que_para_el_scroll="El maquillaje cuarteado en la nariz es un problema que Marisol ve cada mañana."),
reencuadre="El maquillaje falla por los poros, no por la base.",mecanismo="Saca impurezas de noche.",prueba=["Plazo de dos semanas"],objeciones_resueltas=["«¿Cuánto tarda?» → dos semanas"],disparadores_emocionales=["Vergüenza"],tecnicas_persuasion=["Problema visual","Brevedad","Descuento"],
frases_clave=[F("Embarrassed of makeup looking like this","¿Te da vergüenza que la base se te vea así?")],oferta_cta="30 %; 290 días.",
por_que_funciona="15 segundos, 290 días, 10 variantes: el anuncio más corto del ranking. Vive de una sola imagen (base cuarteada) y un solo beneficio.",
senales_de_conversion="8 anuncios, 1 vídeo, 10 variantes, 720 días; 290 días.",
que_copiar_para_nocta=["Ángulo maquillaje para Marisol en 15 s"],que_no_se_puede_decir_en_espana=["«pulls out all impurities» → «absorbe la grasa»"],adaptacion_espana="Marisol."))
A.append(a)
# R28 (hombre, «segunda cita», 26 s)
a=base(28); a.update(dict(traduccion_es="Te enseño cómo pasé de esto a esto. Mira toda la porquería que se ha quedado en el parche. Solo tienes que ponerte el parche, dormir con él, y ahora me lo quito. Tíos, esto es una locura. Por esto tu piel no se ve tan bien como podría. Una rutina que te va a subir el nivel. Y créeme: tu chica lo va a notar. Pruébalo y me lo agradeces en la segunda cita.",
estructura=[E(0,3,"gancho transformación + prueba","let me show you how I took my skin from this to this. Now you can see all the gunk stuck on this nose patch.","Antes/después + parche usado (inferido).","Prueba en el segundo 2."),E(3,14,"uso en tiempo real","apply… go to sleep… I'm about to take it off. Guys, this is insane.","Retirada en cámara (inferido).","Peel reveal en directo."),E(14,26,"beneficio social + cta","your girl's gonna notice… thank me when you're going on your second date","Sonrisa (inferido).","Beneficio de ligar.")],
gancho=dict(tipo="Transformación + peel reveal inmediato",texto_en="let me show you how I took my skin from this to this",texto_es="Te enseño cómo pasé de esto a esto",por_que_para_el_scroll="Antes/después y parche usado en los tres primeros segundos."),
reencuadre="Ninguno: pura demostración.",mecanismo="Ninguno explícito.",prueba=["Retirada del parche en cámara","«Toda la porquería»"],objeciones_resueltas=["«¿Para qué?» → para ligar"],disparadores_emocionales=["Asco satisfactorio","Deseo (segunda cita)"],tecnicas_persuasion=["Demostración en directo","Beneficio social masculino","Humor"],
frases_clave=[F("Guys, this is insane.","Tíos, esto es una locura."),F("thank me when you're going on your second date","me lo agradeces en la segunda cita")],oferta_cta="«Try it now»; 200 días.",
por_que_funciona="13 anuncios y 22 variantes en 26 segundos sin explicar nada: es el anuncio de puro «asco satisfactorio» para hombres, con un beneficio social explícito. Demuestra que para Álex la demostración vale más que la explicación.",
senales_de_conversion="13 anuncios, 3 vídeos, 22 variantes, 644 días; 200 días.",
que_copiar_para_nocta=["Peel reveal en directo en el segundo 3 para Álex","Beneficio social («lo va a notar»)"],que_no_se_puede_decir_en_espana=["Ninguno"],adaptacion_espana="Álex, TikTok."))
A.append(a)
# R29 (3 warning signs, «bestie»)
a=base(29); a.update(dict(traduccion_es="Tres señales de alarma de que tus poros necesitan ayuda ya. Una: la nariz siempre grasa y brillante. Dos: te salen puntos negros aunque tengas rutina. Tres: los poros se te ven grandes en el espejo. Amiga, ahora hay una forma mejor: los parches de nariz de Vue. Adiós poros dilatados, puntos negros, nariz grasa, textura áspera. Poros más limpios, más pequeños, invisibles, con la ciencia coreana detrás. Y lo mejor: 60 días de garantía. Consigue los tuyos.",
estructura=[E(0,3,"gancho listicle urgente","Three warning signs, your pores need immediate help.","Rótulo (inferido).","Urgencia + lista."),E(3,13,"3 señales","oily and shiny… blackheads despite routine… visibly large","Nariz (inferido).","Auto-diagnóstico."),E(13,22,"solución en ráfaga","goodbye enlarged pores, blackheads, oily nose, rough texture","Producto (inferido).","Lista de beneficios."),E(22,27,"garantía + cta","60-day money-back guarantee. Get your… now.","Web (inferido).","Cierre.")],
gancho=dict(tipo="Listicle urgente",texto_en="Three warning signs, your pores need immediate help.",texto_es="Tres señales de que tus poros necesitan ayuda ya.",por_que_para_el_scroll="Lista + urgencia; el vídeo orgánico más visto de Vue en TikTok usa este texto."),
reencuadre="Síntomas → un problema.",mecanismo="Ciencia coreana (genérico).",prueba=["Ninguna visual"],objeciones_resueltas=["«¿Es para mí?»"],disparadores_emocionales=["Urgencia","Complicidad («bestie»)"],tecnicas_persuasion=["Listicle","Ráfaga de beneficios","Tono de amiga"],
frases_clave=[F("Bestie, there's a better way now.","Amiga, ahora hay una forma mejor."),F("you experience blackheads despite having a skincare routine","te salen puntos negros aunque tengas rutina")],oferta_cta="60 días.",
por_que_funciona="27 segundos, 11 anuncios, 20 variantes. Versión rápida y «de amiga» del listicle R9; probada orgánicamente en TikTok antes. Claim «invisibles» a suavizar.",
senales_de_conversion="11 anuncios, 2 vídeos, 20 variantes, 656 días; 161 días.",
que_copiar_para_nocta=["Tono «amiga» para Bea","Probar el texto orgánico primero"],que_no_se_puede_decir_en_espana=["«invisible» → «mucho menos visibles»","«backed by Korean skincare science» → condicional"],adaptacion_espana="Bea."))
A.append(a)
# R30 (novio)
a=base(30); a.update(dict(traduccion_es="Tuve que explicarle a mi novio que esto no son puntos negros. Le vi meses apretándose y frotándose la nariz, frustrado porque nada funcionaba. Al final tuve que intervenir y educarle. Se llaman filamentos sebáceos: tapones de grasa que se forman de forma natural. Chicos, no podéis arrancarlos ni frotarlos como si fueran suciedad. Necesitan un cuidado distinto. Por eso cualquier chica os diría que dejéis de tocaros la cara: lo empeoráis. Así que le compré estos parches coreanos hechos para filamentos, no para puntos negros. Absorben la grasa mientras duerme. Se acabó frotarse con jabón y la piel roja de las tiras que usaba. A las tres semanas su nariz está mucho más lisa. Hasta él admite que yo tenía razón, y créeme, eso no pasa a menudo. Ahora se lo cuenta a sus amigos. Novias de todo el mundo me dan las gracias por conseguir que sus novios escuchen. Y lo mejor: garantía de devolución, sin riesgo. Y ahora hasta un 30 % de descuento más envío gratis.",
estructura=[E(0,4,"gancho relación","I had to teach my boyfriend these aren't blackheads.","Pareja (inferido).","Historia con tercero."),E(4,14,"observación","I watched him squeeze and scrub his nose for months","Él frustrado (inferido).","Espejo para hombres, contado por ella."),E(14,26,"reencuadre + regaño cariñoso","Guys, you can't just rip them out… any girl would tell you to stop picking","Ella a cámara (inferido).","Voz de autoridad doméstica."),E(26,40,"solución + resultado","Korean nose patches… After three weeks, his nose looks so much smoother","Él con parche (inferido).","Prueba con plazo."),E(40,50,"humor + prueba social","Even he admits I was right… Girlfriends everywhere are thanking me","Ambos (inferido).","Doble público."),E(50,57,"garantía + oferta","money back guarantee… 30% plus free shipping","Web (inferido).","Cierre.")],
gancho=dict(tipo="Relación (novia educa a novio)",texto_en="I had to teach my boyfriend these aren't blackheads.",texto_es="Tuve que explicarle a mi novio que esto no son puntos negros.",por_que_para_el_scroll="Historia de pareja con el reencuadre dentro; apela a ella (compradora) y a él (usuario)."),
reencuadre="El del nº 1, contado por un tercero.",mecanismo="Absorbe de noche; sin jabón ni tiras.",prueba=["Tres semanas","«Él admite que tenía razón»","Novias agradecidas"],objeciones_resueltas=["«Los hombres no se cuidan» → ella se lo compra","«¿Duele?» → adiós rojez de tiras"],disparadores_emocionales=["Complicidad de pareja","Humor","Orgullo (tener razón)"],tecnicas_persuasion=["Narración en tercera persona","Doble público","Humor de pareja","Oferta apilada"],
frases_clave=[F("I had to teach my boyfriend these aren't blackheads.","Tuve que explicarle a mi novio que eso no son puntos negros."),F("Even he admits I was right, and trust me, that doesn't happen often.","Hasta él admite que yo tenía razón, y eso no pasa a menudo."),F("Girlfriends everywhere are thanking me","Novias de todo el mundo me dan las gracias")],oferta_cta="30 % + envío gratis + garantía.",
por_que_funciona="184 días, 17 variantes: el guion de pareja convierte porque la mujer compra para el hombre (regalo/cuidado) y el hombre se reconoce sin que le vendan directamente. El humor («no pasa a menudo») da credibilidad.",
senales_de_conversion="8 anuncios, 2 vídeos, 17 variantes, 661 días; 184 días.",
que_copiar_para_nocta=["Guion de pareja para vender a Álex a través de Bea/Marisol","Humor doméstico"],que_no_se_puede_decir_en_espana=["Corea → condicional"],adaptacion_espana="Bea/Marisol con pareja."))
A.append(a)
json.dump(A,open('/tmp/claude-0/-home-user/e4610181-73c9-5b97-9776-a971b4d99e53/scratchpad/vue_study/out/analysis_b2.json','w'),ensure_ascii=False,indent=0)
print('part2 ok',len(A))
