# -*- coding: utf-8 -*-
import json
W={r['rank']:r for r in json.load(open('/tmp/claude-0/-home-user/e4610181-73c9-5b97-9776-a971b4d99e53/scratchpad/vue_study/in/winners_all.json'))}
def base(rank):
    r=W[rank]; return dict(rank=rank,id_video=r['best'],titulo_meta=r['titles'][0] if r['titles'] else '',landing=r['landing'],duracion_s=round(r['duration']),metricas=dict(anuncios=r['ads'],videos=r['videos'],dias_totales=r['total_run'],dias_max=r['max_run'],variantes=r['variants'],primera_fecha=r['first'],ultima_fecha=r['last']),transcripcion_en=r['text'])
def C(rank,tipo,en,es,pq,sen,cop,claims,adapt):
    a=base(rank); a.update(dict(gancho=dict(tipo=tipo,texto_en=en,texto_es=es,por_que_para_el_scroll=""),por_que_funciona=pq,senales_de_conversion=sen,que_copiar_para_nocta=cop,que_no_se_puede_decir_en_espana=claims,adaptacion_espana=adapt)); return a
A=[
C(14,"Orden + advertencia (familia R6)","Stop treating these like blackheads. You might think you can squeeze them out. Please don't","Deja de tratarlos como puntos negros. Crees que puedes sacarlos apretando. Por favor, no",
"Versión de 57 s del guion «tubitos + imán» (R6) que añade la explicación de cómo se forma un punto negro de verdad («cuando se acumula grasa y piel muerta, el tubo se bloquea y se oxida»): es la más didáctica de la familia y aguantó 202 días con 5 grabaciones. Cierra con «backed by scientific research», que en España se sustituye por el argumento del material (hidrocoloide = apósitos).",
"9 anuncios, 5 vídeos, 10 variantes, 837 días; 202 días.",["Explicar la diferencia punto negro / filamento en 8 s","Antes/después + «los resultados son increíbles» (con visual real)"],["«backed by scientific research» → material de apósitos"],"Todos."),
C(18,"Identidad hombre (familia R1)","Most guys think these are blackheads. They're not.","La mayoría de los tíos cree que esto son puntos negros. No lo son.","Versión masculina sin edad del nº 1: 6 grabaciones, 212 días. Confirma que el hombre joven responde al mismo guion que el maduro si la primera frase le nombra.","10 anuncios, 6 vídeos, 16 variantes, 752 días; 212 días.",["Versión Álex de la plantilla maestra"],["Las del nº 1"],"Álex."),
C(22,"Identidad mujer (familia R1)","And these dark spots on your nose aren't blackheads.","Y esos puntitos oscuros de la nariz no son puntos negros.","Mismo guion que el nº 1 con «tons of women»: 30 variantes con un solo vídeo, 190 días. Vue lo mantuvo activo hasta agosto de 2026.","9 anuncios, 1 vídeo, 30 variantes, 712 días; 190 días.",["Multiplicar variantes de texto sobre un vídeo que funciona (30 textos, 1 vídeo)"],["Las del nº 1"],"Marisol."),
C(24,"Orden a hombres (familia R1)","Guys, stop treating these like blackheads.","Chicos, dejad de tratar esto como puntos negros.","El nº 1 con arranque «para de» dirigido a hombres: 9 grabaciones distintas en 6 meses. Es el guion que Vue eligió para regrabar con más creadores masculinos.","11 anuncios, 9 vídeos, 24 variantes, 586 días; 119 días.",["Grabar la plantilla con 3 hombres distintos"],["Las del nº 1"],"Álex."),
C(27,"Identidad mujer 40+ (familia R6)","Women over 40, you have these black dots on your nose","Mujeres de más de 40: tenéis estos puntos en la nariz","«Tubitos + imán» con edad explícita (40+): 198 días. La versión para Marisol de la familia R6.","7 anuncios, 2 vídeos, 7 variantes, 703 días; 198 días.",["Versión Marisol 40+ de «tubitos»"],["Las de R6"],"Marisol."),
C(31,"Anti-láser (familia R19)","I thought laser for my pores was a good idea, but then I found out it could damage my skin permanently.","Pensaba que el láser para los poros era buena idea, hasta que supe que podía dañarme la piel para siempre.","El cuerpo de R19 con gancho de arrepentimiento anticipado; 13 anuncios, 17 variantes, 186 días. Para Marisol, el miedo al daño permanente es más fuerte que el precio.","13 anuncios, 3 vídeos, 17 variantes, 636 días; 186 días.",["Gancho de «casi cometo un error caro»"],["«Dermatologists warn» → sin médicos; «damage permanently» → «puede dañar la barrera»"],"Marisol."),
C(32,"Pregunta + Dúo en 26 s","Want smoother skin by morning? Start here.","¿Quieres la piel más lisa mañana por la mañana? Empieza aquí.","Anuncio de Dúo de 26 s y 291 días: pregunta + «dos pasos» + parche por la mañana enseñado («this is what the patch looks like in the morning»). Molde corto para el Dúo Noche.","8 anuncios, 2 vídeos, 8 variantes, 660 días; 291 días.",["Dúo en 26 s con el parche usado en cámara"],["«minimized my pores in one week» → «en una semana se notaban menos»"],"Bea."),
C(33,"Identidad chicas 20s (familia R6)","Most girls in their 20s think they can squeeze these black dots out. Please don't","La mayoría de las chicas de 20 cree que puede sacarlos apretando. Por favor, no","Añade a la familia R6 los detalles de Bea: herramientas de extracción de TikTok, hacer zoom en la nariz en cada selfie, «el maquillaje se aplica mejor». 22 variantes, 163 días. Es el guion con más detalles de la vida real de Bea.","9 anuncios, 3 vídeos, 22 variantes, 602 días; 163 días.",["Detalles reales de Bea: zoom en selfies, herramientas de TikTok, maquillaje más liso"],["Las de R6"],"Bea."),
C(34,"3 razones (por qué te salen)","Three reasons your pores keep breaking you out.","Tres razones por las que tus poros te siguen dando problemas.","Listicle racional (producto en superficie, ingredientes agresivos, no ir a la raíz) con 289 días y un solo vídeo. Cierra con «tres meses usándolos»: constancia como prueba.","7 anuncios, 1 vídeo, 13 variantes, 636 días; 289 días.",["Listicle de tres causas","«Tres meses usándolos» como prueba de constancia"],["«No harsh chemicals» → «sin activos agresivos»"],"Marisol."),
C(36,"Dato + explicación (24 h)","Your pores refill every 24 hours. That's why your nose never stays matte.","Tus poros se rellenan cada 24 horas. Por eso la nariz nunca se te queda mate.","Gancho de dato («cada 24 horas») que explica el brillo: el mejor guion sobre BRILLO, no sobre puntos. Termina con «200.000+ clientes». 129 días, 14 variantes.","6 anuncios, 2 vídeos, 14 variantes, 602 días; 129 días.",["Ángulo brillo: «por eso nunca se te queda mate»","Dato en el gancho"],["«200,000+ customers» → solo con cifra real de NOCTA"],"Marisol/Álex."),
C(37,"Descubrimiento + prueba inmediata","I finally learned why the dark dots on my nose always come back. Look how much cleaner my nose looks now","Por fin sé por qué me vuelven los puntitos. Mira lo limpia que tengo ahora la nariz","Historia mínima (33 s) que enseña el resultado en el segundo 3 («look how much cleaner»). 26 variantes, 173 días. Modelo de historia corta que empieza por la prueba.","12 anuncios, 2 vídeos, 26 variantes, 567 días; 173 días.",["Resultado en el segundo 3 antes de contar nada"],["Ninguno grave"],"Bea."),
C(38,"Anti-agresivo por edad (familia R19)","Harsh treatments don't age well on the skin.","Lo agresivo envejece mal en la piel.","Gancho de una frase con doble sentido (age well) sobre el cuerpo de R19: 156 días, 6 grabaciones.","8 anuncios, 6 vídeos, 12 variantes, 528 días; 156 días.",["«Lo agresivo envejece mal» para Marisol"],["Sin médicos"],"Marisol."),
C(39,"Empatía («no estás sola»)","I promise you're not alone. For years I thought these dark dots were blackheads.","Te prometo que no estás sola. Durante años pensé que eran puntos negros.","Historia empática (54 s) que reencuadra la culpa («pensé que mi piel estaba sucia»); cierra con «no tienes que conformarte». 21 variantes, 135 días. Funciona con Bea/Marisol que se sienten juzgadas.","12 anuncios, 3 vídeos, 21 variantes, 543 días; 135 días.",["«No estás sola» + quitar la culpa («no es que tu piel esté sucia»)","«Dejé de luchar contra mi piel»"],["Corea → condicional"],"Bea/Marisol."),
C(40,"Dato T-zone","Did you know 80% of your skin oil comes from just your T-zone?","¿Sabías que el 80 % de la grasa de tu cara sale solo de la zona T?","Anuncio de kit T-zone con dato de apertura y prueba por la mañana; 149 días. Para NOCTA es el molde del anuncio de Zona T / Plan por zonas cuando existan barbilla y frente.","9 anuncios, 2 vídeos, 14 variantes, 572 días; 149 días.",["Dato de apertura para vender varias zonas"],["«80 %» → citar fuente o quitar la cifra"],"Marisol."),
C(41,"Transformación paralela (familia R19)","You want to go from blackheads to smooth nose, from oily shine to a matte glow.","Quieres pasar de puntos negros a nariz lisa, de brillo graso a acabado mate.","Cuerpo de R19 sin gancho de edad: 14 anuncios, 23 variantes. Cierra con «hasta 45 %».","14 anuncios, 5 vídeos, 23 variantes, 507 días; 112 días.",["Paralelismo de transformación como gancho"],["Sin médicos"],"Todos."),
C(42,"Curiosidad social","Why is everyone switching to these nose patches? Every time I post my skin, people ask me what product I'm using.","¿Por qué todo el mundo se está pasando a estos parches? Cada vez que subo mi piel me preguntan qué uso.","Prueba social como gancho (la gente pregunta) + «spill the tea». 224 días con 5 anuncios. Para cuando NOCTA tenga comentarios reales.","5 anuncios, 2 vídeos, 10 variantes, 571 días; 224 días.",["Gancho «me preguntan qué uso» cuando haya comentarios reales"],["«ultimate hack» → «el truco»"],"Bea."),
C(43,"Confesión de inseguridad + resumen rápido","I accidentally fixed my biggest insecurity. Those dots, not blackheads.","Arreglé sin querer mi mayor complejo. Esos puntos, no son puntos negros.","24 segundos, 24 anuncios, 33 variantes en 6 meses: la versión ultracomprimida del reencuadre. Ojo: el mismo arranque aparece 19 veces entre los muertos: funciona solo si en el segundo 1 ya se ve la nariz y el resto va a toda velocidad.","24 anuncios, 2 vídeos, 33 variantes, 514 días; 103 días.",["Versión de 24 s: confesión + reencuadre + solución + garantía, sin historia"],["Ninguno grave"],"Bea."),
C(44,"Corea (familia R11)","the Korean innovation changing European skincare. For truly K-Beauty clear skin, the secret lies in what happens while you sleep.","La innovación coreana que está cambiando la cosmética europea: el secreto está en lo que pasa mientras duermes.","Cuerpo K-beauty + «mientras duermes»; 289 días con un vídeo. Solo con lote coreano.","6 anuncios, 1 vídeo, 7 variantes, 582 días; 289 días.",["«El secreto está en lo que pasa mientras duermes»"],["Corea → condicional"],"Bea."),
C(45,"Identidad hombre 20s (familia R1)","Most guys in their 20s think these are blackheads.","La mayoría de los tíos de 20 y pocos cree que esto son puntos negros.","Nº 1 para hombres jóvenes: 207 días. Cierra la matriz de identidades del nº 1 (mujer / hombre / 20s / 35+).","5 anuncios, 3 vídeos, 9 variantes, 538 días; 207 días.",["Versión Álex 20s"],["Las del nº 1"],"Álex."),
C(46,"Miedo al daño (tiras)","Every time you rip off a pore strip, you're damaging your skin. Here's what that damage actually looks like.","Cada vez que te arrancas una tira, te dañas la piel. Así es ese daño.","El anuncio más «médico» de la cuenta: capilares rotos, microdesgarros, inflamación crónica, «por eso tus poros se ven más grandes que hace cinco años». 16 anuncios, 40 variantes en 3 meses. Muy eficaz, pero lleno de claims que en España hay que reescribir (dermatólogos recomiendan, grado médico).","16 anuncios, 4 vídeos, 40 variantes, 462 días; 115 días.",["Ángulo daño acumulado de las tiras (con lenguaje prudente)","«Tus poros se ven más grandes que hace cinco años»"],["«dermatologists recommend» → quitar","«medical grade hydrocolloid» → «hidrocoloide, el material de los apósitos» solo si el proveedor certifica ISO 13485","«broken capillaries, micro tears» → «rojeces e irritación»"],"Marisol."),
C(47,"Recurrencia (familia R4)","If your dark nose dots keep coming back, they're not blackheads.","Si los puntitos de la nariz te vuelven siempre, no son puntos negros.","R4 con gancho de recurrencia; 16 anuncios, 22 variantes.","16 anuncios, 5 vídeos, 22 variantes, 466 días; 121 días.",["Gancho de recurrencia «si te vuelven siempre»"],["Las de R4"],"Todos."),
C(48,"Identidad 40+ con lección","If you're over 40 and still fighting these dark dots on your nose, please watch this.","Si tienes más de 40 y sigues peleándote con los puntitos de la nariz, mira esto.","82 segundos (largo) pero 16 anuncios y 28 variantes: enseña la diferencia punto negro / filamento (color, zona, extracción) y por qué la piel madura no aguanta apretar. Es la «clase» para Marisol.","16 anuncios, 4 vídeos, 28 variantes, 466 días; 75 días.",["Tabla verbal punto negro vs filamento (negro/aislado vs gris/en toda la nariz)","«Más visibles con la edad»"],["Corea → condicional"],"Marisol."),
C(49,"«Por favor, no» (familia R6)","You have these black dots on your nose and you probably think you can squeeze them out. Please don't","Tienes estos puntos en la nariz y seguramente crees que puedes sacarlos apretando. Por favor, no","Regrabación 2025-26 de R6 con «60 día garantía» explícita: 163 días.","9 anuncios, 3 vídeos, 13 variantes, 503 días; 163 días.",["Las de R6"],["Las de R6"],"Todos."),
C(50,"Reacción en directo (hombre)","If you've been squeezing these, congrats you've been doing it wrong… Look, look at all that. Oh my gosh, dude.","Si te los has estado apretando, enhorabuena: lo hacías mal… Mira, mira todo eso. Madre mía.","Anuncio de reacción genuina: un amigo le recomienda, se lo pone, se lo quita en cámara y reacciona («oh my gosh, dude, that was all in my nose»). 14 anuncios, 25 variantes, un solo vídeo. Para Álex, la reacción espontánea vale más que el guion.","14 anuncios, 1 vídeo, 25 variantes, 500 días; 108 días.",["Reacción en directo sin guion para Álex","«Un colega me lo recomendó»"],["Ninguno"],"Álex."),
C(51,"Diagnóstico visual (familia R4)","If your nose looks like this, you don't have blackheads. You have sebaceous filaments.","Si tu nariz se ve así, no tienes puntos negros. Tienes filamentos.","R4 con arranque «si tu nariz se ve así»: 20 anuncios, 30 variantes en 3 meses (vida corta por anuncio, 60 días, pero muchísima rotación).","20 anuncios, 7 vídeos, 30 variantes, 391 días; 60 días.",["Arranque visual «si tu nariz se ve así» + nariz en macro"],["Las de R4"],"Todos."),
C(52,"8 señales (ráfaga)","8 clear signs your nose needs better care: stubborn blackheads, oily shine, large pores…","Ocho señales de que tu nariz necesita más cuidado…","Listicle largo en ráfaga con claims cuantitativos («3× smaller pores, 24-hour oil control, 2× smoother») que en España no se pueden usar. 195 días en 2025.","4 anuncios, 2 vídeos, 9 variantes, 507 días; 195 días.",["Formato ráfaga de síntomas (sin cifras)"],["«3× smaller pores», «24-hour oil control», «2× smoother» → eliminar"],"Marisol."),
C(53,"Cronología 3 semanas","Watch what happens when she stops treating these like blackheads and uses the right patches for three weeks. Week 1… Week 2… Week 3…","Mira lo que pasa cuando deja de tratarlos como puntos negros y usa los parches tres semanas. Semana 1… 2… 3…","Estructura de diario (semana 1, 2, 3) en tercera persona; 114 días, 13 variantes. Molde para el anuncio de «7 noches» y «14 días» de NOCTA.","10 anuncios, 1 vídeo, 13 variantes, 500 días; 114 días.",["Cronología semana a semana con expectativas realistas (semana 1: se afloja; 2: más claros; 3: deja de volver)"],["«the buildup stopped coming back» → «volvía mucho menos»"],"Marisol."),
C(54,"Nariz de fresa + puntos blancos","This got rid of my stubborn sebaceous filaments… I thought I was cursed with a strawberry nose forever.","Esto me quitó los filamentos rebeldes… Pensaba que estaba condenada a la nariz de fresa.","182 días: metáfora «nariz de fresa» + «el residuo blanco te enseña lo que había». Explica la diferencia de grasas entre punto negro y filamento.","8 anuncios, 2 vídeos, 14 variantes, 477 días; 182 días.",["«Nariz de fresa»","«El blanco del parche te enseña lo que había dentro»"],["«got rid of» → «se notan mucho menos»"],"Bea/Marisol."),
C(55,"Hombre maduro con vida real","Wish someone told me this in my 20s, these aren't blackheads… you're a grown man dealing with the same nose issues you had in high school.","Ojalá me lo hubieran dicho a los 20… eres un hombre hecho y derecho con la misma nariz que en el instituto.","22 anuncios, 31 variantes: el guion de Álex 35+ con detalles reales (videollamadas, reuniones, «mi mujer lo notó», «mis compañeros dicen que voy más arreglado»). Prueba social de entorno laboral.","22 anuncios, 4 vídeos, 31 variantes, 416 días; 75 días.",["Detalles de vida real de Álex 35+: videollamadas, reuniones, pareja","«Sin rutina de mañana»"],["Corea → condicional; «100 % risk-free» → «sin riesgo»"],"Álex 35+."),
C(56,"Versión larga de R13","If your nose looks like this, you don't have blackheads. You just have oil plugs in your pores…","Si tu nariz se ve así, no tienes puntos negros. Tienes tapones de grasa…","115 s: la versión larga de R13. 11 anuncios y 88 días: funciona, pero peor por segundo que la de 40 s. Evidencia contra alargar.","11 anuncios, 5 vídeos, 17 variantes, 418 días; 88 días.",["Nada nuevo; confirma 40 s"],["Las de R13"],"—"),
C(57,"Bucle sin fin","If your dark nose dots always come back, stop doing this… It's a never-ending loop.","Si los puntitos te vuelven siempre, deja de hacer esto… Es un bucle sin fin.","Cuerpo de R3 con gancho de recurrencia y cierre «dale un respiro a tu piel»; 119 días, 21 variantes.","9 anuncios, 2 vídeos, 21 variantes, 441 días; 119 días.",["«Bucle sin fin»","«Dale un respiro a tu piel»"],["Corea → condicional"],"Bea/Marisol."),
C(58,"Secreto + escasez (21 s)","This is the secret product that helped me transform my nose… these have sold out four times already.","El producto secreto que me transformó la nariz… se ha agotado cuatro veces.","21 segundos y 223 días con solo 3 anuncios: escasez concreta («cuatro veces agotado») + «se ve funcionando».","3 anuncios, 1 vídeo, 3 variantes, 517 días; 223 días.",["Escasez concreta y verificable (lote piloto)"],["Ninguno"],"Bea."),
C(59,"Stop (familia R3)","If you have dark dots on your nose, stop doing this.","Si tienes puntitos en la nariz, deja de hacer esto.","Tercera grabación de R3 con 6 vídeos: 117 días.","9 anuncios, 6 vídeos, 12 variantes, 377 días; 117 días.",["Las de R3"],["Las de R3"],"Todos."),
C(60,"Pareja en directo (84 s)","I can't believe I didn't notice this last night… Baby, are you wearing my nose patches?","No me lo puedo creer… Cariño, ¿llevas mis parches de nariz?","Vídeo de pareja improvisado (84 s): él usa los parches de ella a escondidas, retirada en cámara, «esto salió de tu nariz», «tú compras el siguiente lote». 111 días con 5 grabaciones. Autenticidad > guion.","6 anuncios, 5 vídeos, 9 variantes, 400 días; 111 días.",["Vídeo de pareja improvisado con retirada en cámara","«Tú compras el siguiente»"],["Ninguno"],"Bea + pareja."),
]
json.dump(A,open('/tmp/claude-0/-home-user/e4610181-73c9-5b97-9776-a971b4d99e53/scratchpad/vue_study/out/analysis_b3.json','w'),ensure_ascii=False,indent=0)
print('part3 ok',len(A))
